'.\" t
.\"     Title: tuxtremsplit
.\"    Author: Guillaume HAIN <zedtux@zedroot.org>
.\"    Manual: Tuxtremsplit Manuel
.\"      Date: 2010-09-24
.\"  Language: English
.\"
.TH "TUXTREMSPLIT" "8" "2010\-09\-24" "TUXTREMSPLIT 3\&.0\&.6\" Tuxtremsplit" Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH NAME
TuXtremSplit - A Linux Xtremsplit file tool.
.SH SYNOPSIS
.sp
\fItuxtremsplit\fR <file>
.sp
\fItuxtremsplit\fR [options]
.SH "DESCRIPTION"
.sp
The goal of this application is to provide an application that manage the Xtm file format created by the Windows software Xtremsplit.\&
.sp
It's a fully compatible application, that work with all xtm files and also with auto-joinable xtm files. It also can verify the MD5 checksums of files, like the Windows version\&.
.RE
.SH OPTIONS
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Display help and exit\&.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version and exit\&.
.RE
.SH BUGS
.sp
https://launchpad.net/tuxtremsplit
.SH AUTEURS
.sp
Developer: Guillaume HAIN <zedtux@zedroot.org>
.sp
Manual: wido <widomaker2k7@gmail.com>
