#!/bin/bash
#DEBHELPER#
# Automatically added by dh_installmime
if [ "$1" = "configure" ] && [ -x "`which update-mime-database 2>/dev/null`" ]; then
	update-mime-database /usr/share/mime
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  tuxtremsplit.public
fi
# End automatically added section

# Install the Xtm file mimetype and associate it to TuXtremSplit
USER_ROOT=true
MIMETYPE_DATABASE_PATH_FOR_ROOT="/usr/share/mime/packages/xtm-mimetype.xml"
MIMETYPE_DATABASE_PATH_FOR_USER="~/.local/share/mime/packages/xtm-mimetype.xml"
DESKTOP_FILE_PATH="/usr/share/applications/tuxtremsplit.desktop"

# Define if the current user have root rights
if [[ $EUID -ne 0 ]]; then
	USER_ROOT=false
fi

# Define the script environement
if [ $USER_ROOT == true ]; then
	echo "You are logged in as root user."
	if [ -f $MIMETYPE_DATABASE_PATH_FOR_ROOT ]; then
		XTM_MIMETYPE_PATH="/usr/share/mime/"
	else
		echo "There is no file $MIMETYPE_DATABASE_PATH_FOR_ROOT !"
	fi
else
	echo "You are logged in as normal user."
	if [ -f $MIMETYPE_DATABASE_PATH_FOR_USER ]; then
		XTM_MIMETYPE_PATH="~/.local/share/mime/"
	else
		echo "There is no file $MIMETYPE_DATABASE_PATH_FOR_USER !"
	fi
fi

# Install the mimetype
if [ "$XTM_MIMETYPE_PATH" != "" ]; then
	if [ -d "$XTM_MIMETYPE_PATH" ]; then
		echo "Updating Mime database from $XTM_MIMETYPE_PATH..."
		update-mime-database $XTM_MIMETYPE_PATH
	
		if [ $USER_ROOT == true ]; then
			MIMETYPE_DATABASE_PATH=$MIMETYPE_DATABASE_PATH_FOR_ROOT
		else
			MIMETYPE_DATABASE_PATH=$MIMETYPE_DATABASE_PATH_FOR_USER
		fi
		
		if [ -f $MIMETYPE_DATABASE_PATH ]; then
			echo "Installing mimetype with xdg-mime using file $MIMETYPE_DATABASE_PATH..."
			xdg-mime install $MIMETYPE_DATABASE_PATH
		else
			echo "ERROR: No file $XTM_MIMETYPE_PATH"
			exit 1
		fi
	
		if [ -f $DESKTOP_FILE_PATH ]; then
			echo "Setting default application for mimetype application/x-extension-xtm..."
			xdg-mime default tuxtremsplit.desktop application/x-extension-xtm
		else
			echo "WARNING: Unable to find the file $DESKTOP_FILE_PATH !"
			echo "You will miss the global menu item"
		fi
	else
		echo "ERROR: Unable to access path $XTM_MIMETYPE_PATH"
		exit 1
	fi
fi

# Try to create a link of TuXtremSplit
TXS_PY_PATH=`which txs`
if [ "$TXS_PY_PATH" != "" ]; then
	TUXTREMSPLIT_PATH=`which tuxtremsplit`
	if [ "$TUXTREMSPLIT_PATH" == "" ]; then
		if [ $USER_ROOT == true ]; then
			TUXTREMSPLIT_PATH=$(dirname $TXS_PY_PATH)
			echo "Creating symbolic link from $TXS_PY_PATH to $TUXTREMSPLIT_PATH/tuxtremsplit"
			ln -s $TXS_PY_PATH "$TUXTREMSPLIT_PATH/tuxtremsplit"
		else
			echo "The symbolic link from $TXS_PY_PATH to $TUXTREMSPLIT_PATH/tuxtremsplit is missing," \
			"but you're not logged in as root, and so it's not possible to create that link."
			exit 1
		fi
	else
		echo "The symbolic link for txs to tuxtremsplit already exists."
	fi
else
	echo "Unable to find txs in you PATH. No symbolic link created."
	exit 1
fi

UPDATE_NOTIFIER_DIR=/var/lib/update-notifier/user.d

if [ -d $UPDATE_NOTIFIER_DIR ] ; then
  if [ `pgrep -x -c nautilus` -ne 0 ];  then
    cp -f /usr/share/tuxtremsplit/tuxtremsplit-restart-required.update-notifier \
        $UPDATE_NOTIFIER_DIR/tuxtremsplit-restart-required
    touch /var/lib/update-notifier/dpkg-run-stamp
  else
    rm -f $UPDATE_NOTIFIER_DIR/tuxtremsplit-restart-required
  fi
fi

if [ "$XTM_MIMETYPE_PATH" != "" ]; then
	echo "Everything seems fine ! You should restart nautilus to finished the installation of the xtm mimetype."
else
	echo "Something have failed in the installation. You should check why."
	exit 1
fi

exit 0
