#!/bin/bash
#DEBHELPER#
# Uninstall the Xtm file mimetype

USER_ROOT=true
MIMETYPE_DATABASE_PATH_FOR_ROOT="/usr/share/mime/packages/xtm-mimetype.xml"
MIMETYPE_DATABASE_PATH_FOR_USER="~/.local/share/mime/packages/xtm-mimetype.xml"
DESKTOP_FILE_PATH="/usr/share/applications/tuxtremsplit.desktop"

# Define the user home dir if not already defined
if [ "$HOME" == "" ]; then
	$HOME="/home/`whoami`"
fi

# Define if the current user have root rights
if [[ $EUID -ne 0 ]]; then
	USER_ROOT=false
fi

# Define the script environement
if [ $USER_ROOT == true ]; then
	echo "You are logged in as root user."
	if [ -f $MIMETYPE_DATABASE_PATH_FOR_ROOT ]; then
		XTM_MIMETYPE_PATH="/usr/share/mime/"
	else
		echo "There is no file $MIMETYPE_DATABASE_PATH_FOR_ROOT !"
	fi
else
	echo "You are logged in as normal user."
	if [ -f $MIMETYPE_DATABASE_PATH_FOR_USER ]; then
		XTM_MIMETYPE_PATH="~/.local/share/mime/"
	else
		echo "There is no file $MIMETYPE_DATABASE_PATH_FOR_USER !"
	fi
fi

# Install the mimetype
if [ "$XTM_MIMETYPE_PATH" != "" ]; then
	if [ $USER_ROOT == true ]; then
		MIMETYPE_DATABASE_PATH=$MIMETYPE_DATABASE_PATH_FOR_ROOT
	else
		MIMETYPE_DATABASE_PATH=$MIMETYPE_DATABASE_PATH_FOR_USER
	fi
	echo "Uninstalling mimetype for xdg-mime using file $MIMETYPE_DATABASE_PATH..."
	xdg-mime uninstall $MIMETYPE_DATABASE_PATH
	
	echo "Removing file $MIMETYPE_DATABASE_PATH"
	rm $MIMETYPE_DATABASE_PATH
	
	echo "Updating Mime database from $XTM_MIMETYPE_PATH..."
	update-mime-database $XTM_MIMETYPE_PATH
fi

# Removing the desktop file
if [ -f $DESKTOP_FILE_PATH ]; then
    echo "Removing desktop file at $DESKTOP_FILE_PATH..."
	rm "$DESKTOP_FILE_PATH"
fi

# Try to remove the link of TuXtremSplit and the txs file
TUXTREMSPLIT_PATH=`which tuxtremsplit`
if [ "$TUXTREMSPLIT_PATH" != "" ]; then
	echo "Removing link $TUXTREMSPLIT_PATH..."
	rm "$TUXTREMSPLIT_PATH"
fi
TXS_PY_PATH=`which txs`
if [ "$TXS_PY_PATH" != "" ]; then
	echo "Removing file $TXS_PY_PATH..."
	rm "$TXS_PY_PATH"
fi

if [ "$XTM_MIMETYPE_PATH" != "" ]; then
	echo "Everything seems fine ! You should restart nautilus to finished the uninstall of the xtm mimetype."
else
	echo "Something have failed in the installation. You should check why."
fi
